# Generated by Django 3.0.5 on 2020-04-04 13:09

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('user_meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('employee_type', models.CharField(choices=[('worker', 'worker'), ('manager', 'manager'), ('finance_manager', 'finance_manager')], db_column='type', db_index=True, default='worker', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('user_id', models.UUIDField(db_index=True, editable=False)),
                ('user_meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('employee_type', models.CharField(choices=[('worker', 'worker'), ('manager', 'manager'), ('finance_manager', 'finance_manager')], db_column='type', db_index=True, default='worker', max_length=15)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
