# Generated by Django 3.0.5 on 2020-04-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_meta',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='historicalemployee',
            old_name='user_meta',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='user_id',
        ),
    ]
